version: '3'
services:
  db:
    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password

    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d # Ruta de importación de la base de datos
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./FSC:/var/www/html/FSC
      - ./SCADA:/var/www/html/SCADA
      - ./includes:/var/www/html/includes
      - ./powermeter:/var/www/html/powermeter
volumes:
  db_data: {}
